### ISSUE TITLE
Builds fine on macOS with rustc 1.13

### ISSUE THREAD

**Issue by tspiteri** [dirs-dev/dirs-rs#18]
The README states that rustc 1.20 is required on macOS, but it's building fine for me using 1.13. I think this is because libc 0.2.48 was not building on 1.13, but libc 0.2.49 has fixed that, presumably thanks to https://github.com/rust-lang/libc/pull/1247.

**Comment by soc** [comment]
Ah, nice! I will re-test this and update the description. Thanks for letting me know, Trevor!

**Comment by soc** [comment]
Hi Trevor, I fixed this in https://github.com/soc/dirs-rs/commit/734138934b16a447e70c1fb3cf29df58213d708f. Thanks for the hint!
