### ISSUE TITLE
WASI support?

### ISSUE THREAD

**Issue by xen0n** [dirs-dev/dirs-rs#19]
Currently this crate doesn't build under WASI due to falling back to Linux for implementation, blocking WASI port of many popular crates.

How about stubbing out everything with `None` or following the XDG spec for now?

**Comment by soc** [comment]
Hi @xen0n,

thanks for opening the issue. Is there some write-up about the APIs available in WASI to have a look at the implementation options?

> following the XDG spec for now

What do you mean by that?

Thanks,

Simon

**Comment by xen0n** [comment]
Hi,

For now there's [this intro doc](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-intro.md), from there more reference material could be reached. Also there's [the `libc` support](https://github.com/rust-lang/libc/blob/master/src/wasi.rs) to look at.

As for XDG, I mean simply copying the Linux behavior of referring to the various `XDG_FOO` environment variables, as WASI in its current form doesn't have most things stabilized, but does have the environment variables.

**Comment by soc** [comment]
> For now there's this intro doc, from there more reference material could be reached. Also there's the libc support to look at.

Just looked at it. :-)

> As for XDG, I mean simply copying the Linux behavior of referring to the various XDG_FOO environment variables, as WASI in its current form doesn't have most things stabilized, but does have the environment variables.

So basically we add another platform and replace the reading-env-vars-on-Linux API with the reading-env-vars-on-wasi-API?

**Comment by xen0n** [comment]
> So basically we add another platform and replace the reading-env-vars-on-Linux API with the reading-env-vars-on-wasi-API?

I'm afraid that would prematurely make XDG the de-facto standard on WASI, where people actually have the chance to rethink almost everything. So that's why I'm asking for maintainer's decision about whether to stub everything with `None` or not...

**Comment by soc** [comment]
Mhh, I think what would best if WASI offered an API for applications to get their config/cache/data directory directly.

History has proven time and time again that people can't be bothered to implement things correctly if they aren't given an API that does everything for them.

**Comment by xen0n** [comment]
Yeah, then I think we should go the stub route for now, waiting for the APIs to be designed and stabilized? Currently there's so few WASI apps out there, that doing this wouldn't matter.

**Comment by soc** [comment]
I just filed https://github.com/CraneStation/wasmtime/issues/140, I think it is crucial to have this in place before everyone starts writing their own abstractions (and gets it wrong).

For getting things to compile, I think stubbing everything with `None` is an acceptable solution for now.

**Comment by soc** [comment]
I think this has been resolved, for now!
