### ISSUE TITLE
New major release?

### ISSUE THREAD

**Issue by pickfire** [dirs-dev/dirs-rs#21]
I just noticed that there are a new major release dirs 2.0.0 but I cannot find how it differs from 1.0.0 (specifically looking for breaking changes). Any idea? Note that having `1.0` in lock file does not install `2.0`.

**Comment by soc** [comment]
Hi Ivan,

I think the only change visible from the outside is detailed in the changelog: https://github.com/soc/dirs-rs#changelog (the old way we retrieved user dirs made it hard to detect faulty user dir entries, new way does it correctly now).

Let me know if you have any questions!

Cheers,

Simon

**Comment by pickfire** [comment]
Ah, nice. Thanks a lot. It is clarified now.

**Comment by soc** [comment]
Cheers, happy to help!
