### ISSUE TITLE
does not work with rustc 1.13 as documented

### ISSUE THREAD

**Issue by tspiteri** [dirs-dev/dirs-rs#25]
`cfg-if` 0.1.10 requires a later rustc, so dirs-2.0 does not work with rustc 1.13 even though it is documented to work. I think `cfg-if` 0.1 is also a transitive dependency through for example the chain `dir-sys`, `redox_users`, `failure`, `backtrace`, `cfg-if`.

**Comment by tspiteri** [comment]
I tripped on this when testing my crate that also has a documented minimum rustc version 1.13. I had not worried about depending on dirs because it says it supports 1.13. However I realize that it might not be worth the work to maintain this guarantee. However, if this guarantee is not maintained, the documentation should be updated to remove it.

I guess it is possible to not depend on `cfg-if` in `dirs` itself, maybe use something like
```rust
#[cfg(target_os = "windows")]
mod win;
#[cfg(target_os = "windows")]
use win as sys;
// ...
```
instead of
```rust
cfg_if! {
    if #[cfg(target_os = "windows")] {
        mod win;
        use win as sys;
    } else // ...
```

I haven't looked at `dir-sys` itself, which might be similar. But then there is `redox_users`, which unlike `libc` (rustc 1.13) and `winapi` (rustc 1.6) does not document the minimum rustc version supported, so it makes it a little difficult to deal with. Since the redox dependency is conditional in Cargo.toml, maybe it doesn't affect other platforms, so I think it might be enough to simply state that the minimum rustc version is 1.13 for Linux, Mac and Windows, but not for Redox.

**Comment by tspiteri** [comment]
I also looked at `dirs-sys` and it could be changed to not use `cfg-if`. I hacked at it for a short time and got it to compile on GNU/Linux with rustc 1.13. Basically use something like:
```rust
#[cfg(all(unix, not(any(target_os = "macos", target_os = "ios"))))]    
mod xdg_user_dirs;

#[cfg(all(unix, not(any(target_os = "macos", target_os = "ios"))))]    
mod target_unix_not_mac {
    use super::xdg_user_dirs;
    // ...
    pub fn user_dir(user_dir_name: &str) -> Option<PathBuf> // ...
}
#[cfg(all(unix, not(any(target_os = "macos", target_os = "ios"))))]    
pub use self::target_unix_not_mac::{user_dir, user_dirs};
```

If you think something like that can be helpful, I may find some time to work on a PR this week.

**Comment by soc** [comment]
Hi Trevor,

yes, a pull request would be really appreciated! Thanks for bringing this up!
