### ISSUE TITLE
XDG_BIN_HOME isn’t a standard

### ISSUE THREAD

**Issue by flying-sheep** [dirs-dev/dirs-rs#27]
Hi! I just saw you support XDG_BIN_HOME, which is a proposal, but not yet a standard. There’s some 2017 patches that haven’t been merged. I’d like to know why you decided to support it, because it would be cool to be able to rely on it.

**Comment by soc** [comment]
Hi Philipp!

I added what I'd say is pretty much an established pattern in the wild, there wasn't much thought put into it.

Although your question made me think about whether the whole ".local/share" thing wasn't a good idea from the start (and `XDG_BIN_HOME` is now further perpetuating it), and whether it would have been better to have something like `XDG_LOCAL_HOME` pointing to ".local" ... (I guess the XDG spec is not that great in various ways, but it's way to late to change existing things.)

Anyway: I planned on forking the whole spec into a maintained version for a while now; with better documentation that also covers best practices on macOS and Windows  ([unfinished website](https://dirs.dev/)), but haven't managed the motivation to finally do it.

(Especially in the light of https://github.com/flatpak/flatpak.github.io/issues/191#issuecomment-412879458.)

**Comment by flying-sheep** [comment]
> I guess the XDG spec is not that great in various ways, but it's way to late to change existing things.

vastly better than nothing though :smile:

> Anyway: I planned on forking the whole spec into a maintained version for a while now; with better documentation that also covers best practices on macOS and Windows

Sounds nice, and much better than puzzling together this stuff on one’s own. But can you clarify what you mean with “I added what I'd say is pretty much an established pattern in the wild”?

Did you simply add a variable that sounds like it makes sense or are people actually using it?

**Comment by soc** [comment]
It seems quite a lof of people use ".local./bin" for applications, and some distributions have added it to `$PATH`. The decision to support the env variable `$XDG_BIN_HOME` was made based on https://lists.freedesktop.org/archives/xdg/2017-August/013943.html.

(There is also a [proposal](https://wiki.debian.org/XDGBaseDirectorySpecification) ([mail](https://lists.freedesktop.org/archives/xdg/2017-April/013879.html), [mail](https://lists.freedesktop.org/archives/xdg/2016-December/013803.html)) for `$XDG_STATE_HOME`, but I haven't investigated this any further.)

**Comment by flying-sheep** [comment]
Yeah, I think supporting .local/bin makes a lot of sense, since it is in $PATH by default for a few linux distributions and a few programs install into there.

I personally wouldn’t start relying on a suggested standard addition from 2 years ago that since has lost steam and is supported by nobody else …

**Comment by soc** [comment]
@flying-sheep I'm closing this, as the spec has finally been updated to include `XDG_BIN_HOME`.

**Comment by PoignardAzur** [comment]
@soc Hey, I'm currently writing a report on the whole "cargo doesn't do XDG" situation.

Do you have a link to a document stating that XDG_BIN_HOME is now standard? Neither [the archilinux wiki page](https://wiki.archlinux.org/title/XDG_Base_Directory) nor [the freedesktop page](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) mention it.

**Comment by soc** [comment]
Hey @PoignardAzur not sure to be honest. Hasn't maintenance of the spec been abandoned for like 15 years already?

**Comment by PoignardAzur** [comment]
So what did you mean by this?

> I'm closing this, as the spec has finally been updated to include XDG_BIN_HOME.

**Comment by soc** [comment]
Maybe I confused `XDG_BIN_HOME` with `XDG_STATE_HOME` ... :thinking:
