### ISSUE TITLE
template_dir() for MacOS

### ISSUE THREAD

**Issue by axetroy** [dirs-dev/dirs-rs#28]
I found this directory under MacOS: `/Library/User Template`

```bash
open "/Library/User Template"
```

Does MacOS have a template directory like Windows?

**Comment by soc** [comment]
Interesting – I think it would make sense to figure out whether the semantics are comparable.

I think on both Linux and Windows they act as a directory that is used to provide additional for "new file" context menus. Is it the same on macOS?

**Comment by soc** [comment]
I don't think it's comparable: https://derflounder.wordpress.com/2019/10/14/the-macos-user-template-directories-have-a-new-filesystem-location-on-macos-catalina/

I#ll close this for now, but please feel free to reopen with new information!
