### ISSUE TITLE
Remove cfg-if

### ISSUE THREAD

**Issue by dvc94ch** [dirs-dev/dirs-rs#33]
Related discussion #32

**Comment by ArekPiekarz** [comment]
I'll just add to the discussion that right now my project depends indirectly on cfg-if and trying to update dirs to 3.0.0 causes cfg-if to be downgraded from 0.1.10 to to 0.1.9. I would be interested in dirs-rs either unpinning the exact patch version or removing it.

**Comment by soc** [comment]
Fixed in v3.0.1.
