### ISSUE TITLE
MacOS $XDG_*

### ISSUE THREAD

**Issue by OJFord** [dirs-dev/dirs-rs#35]
Please use `$XDG_*` directories on MacOS if they are set, at least.

Many users, including myself, do use them on MacOS, and it's annoying when they're not only not respected, but not respected in a sort of telling me I'm on MacOS not Linux and therefore doing it wrong and should be using some sort of `~/Application Support/Library/Resources/Content/MacOS/Content Library/Who Knows What/Nonsense` instead 🙂.

**Comment by soc** [comment]
Sorry, no.
This was already discussed and rejected here: https://github.com/dirs-dev/directories-rs/issues/47#issuecomment-478337412
