### ISSUE TITLE
Thoughts on testing `dirs::config_dir()` on Windows?

### ISSUE THREAD

**Issue by martinvonz** [dirs-dev/dirs-rs#38]
[My project](https://github.com/martinvonz/jj) expects the user to put their config in a subdirectory of `dirs::config_dir()`. When testing my tool, I want to write a config file to a temporary directory and have the tool read that config. On Linux and Mac, I can do that by pointing `$HOME` to a temporary directory, but what do I do for Windows? https://docs.rs/dirs/4.0.0/dirs/fn.config_dir.html says that the path on Windows is `{FOLDERID_RoamingAppData}`. Is there a way to override that in my tests? I'm not asking for a change in the library.

I can of course define a custom environment variable (e.g. `$JJ_CONFIG`) and make my tool prefer that over `dirs::config_dir()`, and there are probably good reasons I'll want to have that functionality anyway (e.g. to let the user temporarily ignore their regular config).

**Comment by soc** [comment]
Hi @martinvonz,

I'd say that using an application-specific override might be the best approach for all the reasons you mentioned!

Cheers,

Simon
