### ISSUE TITLE
(Not really a bug) option-ext used in dirs-sys adds an MPL license requirement

### ISSUE THREAD

**Issue by emk** [dirs-dev/dirs-rs#51]
Good morning, and thank you for maintaining a very useful Rust crate!

This isn't really a bug report—it's more of a "Hey, I noticed something interesting and thought I'd mention it."

When I updated to the latest `dirs`, I received an interesting "heads up" from `cargo deny`, which noticed that `dirs-sys` uses `option-ext`, which is licensed under the MPL license. The MPL license is a bit of an odd duck: It's a fairly complex file-level copyleft, and it's used infrequently for Rust crates. I'd normally only expect to see if for code extracted from Firefox.

This doesn't represent a serious problem—I can add an exception to our license checker for this and verify it with the right people, at least for the affected project. It isn't necessary to do anything here!

```
error[rejected]: failed to satisfy license requirements
  ┌─ option-ext 0.2.0 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft
  │
  = option-ext v0.2.0
    └── dirs-sys v0.4.1
        └── dirs v5.0.1
```

On the other hand, `option-ext` is a tiny library. So if you're interested, I'd be happy to submit a PR removing this dependency. But that's entirely up to you. This isn't really a bug report, or even really a request—it's more of a "heads up" that you can happily ignore. :-) Please feel free to close it.

Anyway, thank you once again for maintaining a very useful crate!

**Comment by emk** [comment]
For anyone who finds this issue via web search, you can work around this by adding the MPL-2.0 to your `allow` list:

```toml
allow = [..., "MPL-2.0"]
```

Or if you just want to allow it in this one case, you can add an exception:

```toml
[[licenses.exceptions]]
allow = ["MPL-2.0"]
name = "option-ext"
```

**Comment by soc** [comment]
Hi Eric,

thanks for your kind offer, but see https://github.com/dirs-dev/dirs-sys-rs/issues/21#issuecomment-1531528155.

Cheers,

Simon

**Comment by emk** [comment]
Oh, no problem! I didn't see that earlier discussion.

I only raised the issue because I've had to deal with lawyers and the MPL before and it can sometimes be a bit of a headache, even in open source projects. But I see that this is your long-term plan for most of your crates, so no problems!
