### ISSUE TITLE
[Windows] Add user writeable fonts folder

### ISSUE THREAD

**Issue by RouHim** [dirs-dev/dirs-rs#52]
Hey guys,
since windows 10 there is a user writable location for fonts: `%localappdata%\Microsoft\Windows\Fonts`.
Might be worth adding it.

There is also a constant in the windows create for it:
`windows::Win32::UI::Shell::FOLDERID_Fonts`

Greetings

Resources: 

- https://answers.microsoft.com/en-us/windows/forum/all/windows-10-fonts-folder/40616542-c0a4-417a-838e-3eab4294d825
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/constant.FOLDERID_Fonts.html

**Comment by soc** [comment]
Sorry, sadly fonts dirs on Windows don't work the way one would hope. :-/

See https://github.com/dirs-dev/dirs-rs/issues/37#issuecomment-1010003376.
