### ISSUE TITLE
data_dir seems to wrongly be local.

### ISSUE THREAD

**Issue by gl-yziquel** [dirs-dev/dirs-rs#58]
This is a bug coming from the `just` tool:

https://github.com/casey/just/issues/2212

It seems that data_dir() returns some local folder such as `/home/mini-me/.local/share` and not some system wide folder such as `/usr/local/share`.

Maybe there is something that I don't quite get, but this seems to more or less be intended behaviour, when looking at the codebase of dirs-rs.

**Comment by soc** [comment]
Correct.

There are some platforms (like Windows) that distinguish(ed) between user data that's stored on the machine and user data that is associated with a user account and synced to the machine when the user logs in.

`data_dir` vs. `data_local_dir` allows you to select the appropriate one, even if it may not make a difference on the operating system you are currently running on.  
(Similar with `config_dir` vs. `preferences_dir`.)
