### ISSUE TITLE
Does version 5.0.0 introduce any breaking changes?

### ISSUE THREAD

**Issue by aljazerzen** [dirs-dev/dirs-rs#59]
I've just updated from version 4.x to 5.x. Is there any breaking changes in 5.x?

If not, could you, in the future, release such updates in a minor release (4.1 in this case).

Minor releases are meant for new features that are not-breaking. Most crates will depend on this crate only by the major version, so their projects will get the new minor version without any develop input. This is the great thing about semver.

**Comment by soc** [comment]
The big change was the migration from winapi to windows-sys in the transitive dependency of dirs-sys, that might matter for some people.
